apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world-deployment
  annotations:
    pod-info.details.html.spinnaker.io/link: "<a href='https://whatthecommit.com/{{ name }}'>Application dashboard</a>"
  namespace: '${ parameters.namespace }'
spec:
  replicas: '${ #toInt( parameters.replicacount ) }'
  selector:
    matchLabels:
      app: hello-world
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: "Recreate"
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - image: docker.io/ftamas/hello_world_service:v3
          name: hello-world
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: hello-world-config
