apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  ports:
    - port: 80
      targetPort: 80
      name: api
  selector:
    app: hello-world
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: docker.io/ftamas/hello_world:v2
        ports:
        - containerPort: 80
          name: api
