apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: ${ parameters.namespace }
  labels:
    app: hello-world
spec:
  ports:
    - port: 80
      targetPort: 80
      name: api
  selector:
    app: hello-world
  clusterIP: None
