apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-config
  annotations: 
    strategy.spinnaker.io/versioned: 'true'
    attempt.details.html.spinnaker.io/number: 1
  namespace: '${ parameters.namespace }'
data:
  NAMESPACE: '${ parameters.namespace }'
  bgcolor: white
  fgcolor: black
