apiVersion: v1
kind: Service
metadata:
  name: hello-world
  annotations:
    attempt.details.html.spinnaker.io/number: 1
  namespace: '${ parameters.namespace }'
  labels:
    app: hello-world
spec:
  ports:
    - port: 80
      targetPort: 80
      name: web
  selector:
    app: hello-world
  type: ClusterIP
