apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-hello-world-config
  annotations: 
    strategy.spinnaker.io/versioned: 'true'
    attempt.details.html.spinnaker.io/number: 1
  namespace: {{ .Release.Namespace }}
data:
  bgcolor: white
  fgcolor: black
